name: test_datm_lnd

on:
  push:
    branches: [ feature/build ]
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
    branches: [ feature/build ]
  schedule:
    - cron: '0 0 * * MON'
    - cron: '0 0 * * FRI'
  workflow_dispatch:
  
jobs:
  latest-stable:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        test: [test_datm_lnd]
    
    env:
      # set token to access gh command
      GH_TOKEN: ${{ github.token }}
      # installation location for application
      APP_INSTALL_DIR: ${{ github.workspace }}/app
      # installation location for dependencies
      DEP_INSTALL_DIR: ~/.spack-ci
      # option for retention period for artifacts, default is 90 days
      ARTIFACTS_RETENTION_PERIOD: 2

    steps:
      # test component
      - name: Test Component
        uses: esmf-org/nuopc-comp-testing@v1.0.0
        with:
          app_install_dir: ${{ env.APP_INSTALL_DIR }}
          artifacts_files: |
            ${{ env.APP_INSTALL_DIR }}/run/PET*
            ${{ env.APP_INSTALL_DIR }}/run/*.txt
            ${{ env.APP_INSTALL_DIR }}/run/*.log
            ${{ env.APP_INSTALL_DIR }}/run/comp.test.lnd.out.2000-01-01-75600.*
          baseline_files: |
            ${{ env.APP_INSTALL_DIR }}/run/comp.test.*.nc
          cache_input_file_list: |
            ${{ env.APP_INSTALL_DIR }}/run/INPUT
            ${{ env.APP_INSTALL_DIR }}/run/fd_nems.yaml
          component_build: |
            export PATH=${{ env.DEP_INSTALL_DIR }}/view/bin:$PATH
            export ESMFMKFILE=${{ env.DEP_INSTALL_DIR }}/view/lib/esmf.mk
            export NetCDF_ROOT=${{ env.DEP_INSTALL_DIR }}/view
            export FC=gfortran
            cd ${{ env.APP_INSTALL_DIR }}/noahmp
            mkdir build
            cd build
            cmake -DCMAKE_INSTALL_PREFIX=${{ env.APP_INSTALL_DIR }} -DOPENMP=ON ../
            make
            make install
          component_module_name: lnd_comp_nuopc
          data_component_name: datm
          dependencies: |
            zlib@1.2.12
            fms@2022.04
            esmf@8.4.0b15+parallelio
            parallelio@2.5.8+pnetcdf
          dependencies_install_dir: ${{ env.DEP_INSTALL_DIR }}
          test_definition: ${{ env.APP_INSTALL_DIR }}/noahmp/.github/workflows/tests/${{ matrix.test }}.yaml
